name: Node.js CI

on:
  workflow_run:
    workflows: ["Sonar Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./car-search-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies

        run: npm install
      - run: npm run build --if-present
      - run: npm run test
