name: Jest Unit Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./car-search-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies

        run: npm install
      - run: npm run build --if-present
      - run: npm run test

sonarCloudTrigger:
  name: SonarCloud Trigger
  needs: [build]
  runs-on: ubuntu-latest
  # if: ${{ github.event.workflow_run.conclusion == 'success' }}
  steps:
    - name: Clone Repo
      uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
